spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5433/store
    username: fara
    password: password
stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD,EUR,KZT
payment-gateway: stripe